data <- readRDS('animal_data.rds')
breeds <- sort(c("all","domestic sh", "maltese", "american staff", "dachshund",
            "bruss griffon", "eng sprngr span", "bichon frise",
            "pekingese", "basset hound", "labrador retr", "golden retr",
            "poodle min", "siamese", "jack russ ter", "aust shepherd",
            "rottweiler", "pit bull", "collie smooth", "schnauzer min",
            "chihuahua sh", "germ shepherd", "shih tzu", "poodle toy",
            "french bulldog", "eng setter", "pomeranian", "boxer",
            "siberian husky", "domestic mh", "domestic lh", "chow chow",
            "welsh corgi car", "aust cattle dog", "beagle", "min pinscher",
            "pug", "mastiff", "brittany", "eng bulldog", "cavalier span",
            "yorkshire terr", "doberman pinsch", "tr walker hound", "alaskan husky",
            "amer sh", "border collie", "rat terrier", "shiba inu",
            "chinese sharpei", "scot terrier", "amer bulldog", "bernese mtn dog",
            "feist", "sc wheat terr", "samoyed", "welsh corgi pem", "havanese",
            "cocker span","boston terrier", "airedale terr", "papillon", "redbone hound",
            "greyhound", "japanese chin", "shetld sheepdog", "bluetick hound",
            "ital greyhound", "fox terr wire", "bloodhound", "bull terrier",
            "collie rough", "himalayan", "cairn terrier", "bullmastiff", 
            "west highland", "old eng bulldog", "weimaraner", "cane corso",
            "great dane", "amer eskimo", "poodle stnd", "lhasa apso", "persian",
            "maine coon", "eng shepherd", "port water dog", "bengal", 
            "toy fox terrier", "dachshund wh", "rhod ridgeback", "dalmatian",
            "am pit bull ter", "bernese hound","flat coat retr", "black/tan hound",
            "schnauzer stand", "st bernard rgh", "bulldog", "parson russ ter",
            "belg tervuren","staffordshire","eng pointer","akita","presa canario",
            "newfoundland","irish terrier","norwich terrier","germ sh point",
            "alask malamute","manx","fox terr smooth","welsh terrier","great pyrenees",
            "clumber span","eng coonhound","affenpinscher","norw elkhound","dachshund lh",
            "basenji","chihuahua lh","chinese crested","border terrier","pointer",
            "irish wolfhound","ragdoll","black mouth cur","st bernard smth","catahoula",
            "snowshoe","chesa bay retr","oldeng sheepdog","angora","norwgn forest",
            "belg malinois","scottish fold","plott hound","bearded collie","finnish spitz","burmese",
            "aust terrier","vizsla","polish lowland","alask klee kai","harrier",
            "irish setter","sphynx","silky terrier","tonkinese","whippet","schnauzer giant",
            "treeing cur","tibetan span","afghan hound","rex","norfolk terrier",
            "japan bobtail","korat","schipperke","ns duck tolling","queensland heel","tibetan terr",
            "skye terrier","saluki","sussex span","belg sheepdog","keeshond","scot deerhound",
            "welsh spr span","otterhound","birman","eng cocker span","coton de tulear",
            "gordon setter","amer water span","bouv flandres","amer curl lh","manchester terr",
            "borzoi","somali","amer foxhound","lakeland terr","cesky terrier","turkish angora",
            "bedlington terr","terrier","turkish van","boykin span","gr swiss mtn","pbgv",
            "german pinscher","russian blue","aust kelpie","irish watr span","ocicat",
            "germ wh point","pharaoh hound","bombay","mix","dandie dinmont",
            "kerry blue terr","wh pt griffon","akbash","eng foxhound","abyssinian",
            "dutch shepherd","jack russ terr","great pyreneese","carolina dog",
            "egyptian mau","anatol shepherd","dogue de bordx","span water dog",
            "swiss hound","ibizan hound","komondor","hound","german pinsch",
            "dachshund sh","kuvasz","canaan dog","balinese","puli","field spaniel",
            "jindo","curlycoat retr","patterdale terr","exotic sh","lowchen",
            "ocherese","munsterlander","norw buhund","neapolitan mast","beauceron",
            "eng toy spaniel","karelian bear","oriental sh","munchkin lh","british sh",
            "dogo argentino","cornish rex","sealyham terr","devon rex","chartreux",
            "blue lacy","savannah","tibetan mastiff","spinone ital","spanish mastiff",
            "leonberger","podengo pequeno","hovawart","tenn tr brindle","landseer",
            "dutch sheepdog","fila","briard","munchkin sh","gbgv","bull terr min",
            "wolf hybrid","cirneco","picardy sheepdg","entlebucher","cymric",
            "tosa","amer curl sh","pixiebob sh","amer wirehair","pixiebob lh",
            "havana brown","european sh","boerboel","glen of imaal",
            "colorpoint","pumi","javanese"))
